<?php

namespace GudetamaFranceBundle\Entity;

/**
 * UploadSubtitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadSubtitleRepository extends \Doctrine\ORM\EntityRepository
{
}
