users_user:
    resource: "@UsersUserBundle/Resources/config/routing.yml"
    prefix:   /

gudetama_france:
    resource: "@GudetamaFranceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# app/config/routing.yml
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"