# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
imports:
    - { resource: "@UsersUserBundle/Resources/config/security.yml" }
    
security:
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
        # pour admin: app/console fos:user:promote ROLE_SUPER_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        # droits Gudetama a modifier
        - { path: ^/get_playlist_youtube, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/upload_subtitle, role: ROLE_USER }
        - { path: ^/video, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/video_show/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        