gudetama_france_homepage:
    path:     /
    defaults: { _controller: GudetamaFranceBundle:Default:index }
    
youtube_homepage:
    path:     /get_playlist_youtube
    defaults: { _controller: GudetamaFranceBundle:Default:getPlaylistYoutube }

gudetama_france_upload_subtitle:
    path:     /upload_subtitle
    defaults: { _controller: GudetamaFranceBundle:UploadSubtitle:upload_subtitle }

gudetama_france_video:
    path:     /video
    defaults: { _controller: GudetamaFranceBundle:Video:show }

gudetama_france_video_form:
  pattern:   /video_show/{id}
  defaults:  { _controller: GudetamaFranceBundle:VideoForm:index }